import { FIELD_TYPES } from './fieldTypes';

export const ITEM_FORM_CONFIG = [
  {
    key: 'name',
    label: 'Ідентифікатор партії',
    type: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'sender_name',
    label: 'Назва відправника',
    type: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'sender_address',
    label: 'Адреса відправника',
    type: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'sender_contact',
    label: 'Контактна особа відправника',
    type: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'sender_phone',
    label: 'Контактний телефон відправника',
    type: FIELD_TYPES.MASK,
    inputMask: '+(999) 999-9999',
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'recipient_name',
    label: 'Назва отримувача',
    type: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'recipient_address',
    label: 'Адреса отримувача',
    type: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'recipient_contact',
    label: 'Контактна особа отримувача',
    type: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'recipient_phone',
    label: 'Контактний телефон отримувача',
    type: FIELD_TYPES.MASK,
    inputMask: '+(999) 999-9999',
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'volume',
    label: 'Об\'єм партії, м3',
    type: FIELD_TYPES.NUMBER,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'weight',
    label: 'Вага партії, кг',
    type: FIELD_TYPES.NUMBER,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'temperature',
    label: 'Температурний контроль',
    type: FIELD_TYPES.SELECT,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'comment',
    label: 'Коментар',
    type: FIELD_TYPES.TEXTAREA,
    class: 'field col-12',
  },
];
